# Generated by Django 5.0.3 on 2024-03-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='username',
            field=models.CharField(default='gvuyvv', max_length=250),
            preserve_default=False,
        ),
    ]
