# Generated by Django 5.0.3 on 2024-03-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default='1990'),
            preserve_default=False,
        ),
    ]
