# Generated by Django 5.0.3 on 2024-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(default='@admin', max_length=500),
            preserve_default=False,
        ),
    ]
