# Generated by Django 5.0.3 on 2024-03-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_delete_review_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.TextField(),
        ),
    ]
