# Generated by Django 5.0.3 on 2024-03-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_alter_movie_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=250)),
                ('moviereview', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
