# Generated by Django 5.0.3 on 2024-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default='@admin'),
            preserve_default=False,
        ),
    ]
