# Generated by Django 5.0.3 on 2024-03-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_alter_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default='234'),
            preserve_default=False,
        ),
    ]
