# Generated by Django 5.0.3 on 2024-03-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_review_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='movie',
            name='moviereview',
            field=models.CharField(default='@admin', max_length=250),
            preserve_default=False,
        ),
    ]
