# Generated by Django 5.0.3 on 2024-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0017_delete_review_movie_moviereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
