# Generated by Django 5.0.3 on 2024-03-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
