# Generated by Django 5.0.3 on 2024-03-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='image',
            new_name='img',
        ),
    ]
