# Generated by Django 5.0.3 on 2024-03-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_alter_bio_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='biography',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
