# Generated by Django 5.0.3 on 2024-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_alter_bio_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='biography',
            field=models.TextField(),
        ),
    ]
