# Generated by Django 5.0.3 on 2024-03-08 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_alter_bio_biography'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
